import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useAccount } from "wagmi";
import Web3 from "web3";
import jsonInterface from "../Twitter.json";
import logo from "../assets/images/logo.png";
import avi1 from "../assets/images/avi1.png";
import avi2 from "../assets/images/avi2.png";
import {
  AppBar,
  Avatar,
  Box,
  Button,
  Card,
  CardActions,
  Container,
  IconButton,
  Grid,
  Stack,
  TextField,
  Toolbar,
  Typography,
} from "@mui/material";
import Image from "next/image";
import FavoriteBorderOutlinedIcon from "@mui/icons-material/FavoriteBorderOutlined";
import FavoriteIcon from "@mui/icons-material/Favorite";
interface CommentProps {
  author: string;
  content: string;
  id: number;
  likes: number;
  timestamp: number;
  __length__: number;
}

const ca = "0xcfaddf26c7732888d935717a23bac5af64fe86fc";

const Home: NextPage = () => {
  const { address, isConnected } = useAccount();
  const [web3, setWeb3] = useState<Web3 | null>(null);
  const [contract, setContract] = useState<any>(null);
  const [post, setPost] = useState<string>("");
  const [comments, setComments] = useState<CommentProps[]>([]);

  async function createTweet() {
    if (!post.length) return;
    if (contract) {
      alert("Please enter");
      try {
        const send = await contract.methods
          .createTweet(post)
          .send({ from: address });
        if (send) {
          setPost("");
        }
      } catch (error) {
      } finally {
        displayTweets(address as string);
      }
    } else {
      alert("Could not find contract. Please try again later.");
    }
  }

  async function displayTweets(userAddress: string) {
    const tweets = await contract.methods.getAllTweets(userAddress).call();
    setComments(tweets);
  }

  async function likeTweet(userAddress: string, id: number) {
    const tweet = await contract.methods.likeTweet(userAddress, id).send({
      from: address,
    });
  }

  useEffect(() => {
    if (typeof window !== "undefined" && isConnected) {
      const web3Instance = new Web3(window.ethereum);
      setWeb3(web3Instance);

      const contractInstance = new web3Instance.eth.Contract(
        jsonInterface.abi,
        ca
      );
      setContract(contractInstance);
    }
  }, [isConnected]);

  useEffect(() => {
    if (contract && address) {
      displayTweets(address);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [address, contract]);

  console.log(comments);

  return (
    <Box>
      <Head>
        <title>TwitterDapp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <AppBar position="static" elevation={1}>
        <Toolbar>
          <Box
            sx={{
              display: "flex",
              flex: 1,
              justifyContent: "space-between",
            }}
          >
            <Image src={logo} alt="Logo" height={80} />
            {isConnected && (
              <Box sx={{ alignSelf: "center " }}>
                <ConnectButton />
              </Box>
            )}
          </Box>
        </Toolbar>
      </AppBar>
      <Container maxWidth="sm">
        {!isConnected && (
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              minHeight: "100vh",
            }}
          >
            <Image src={logo} alt="Logo" height={200} />
            <ConnectButton />
          </Box>
        )}
        <Card variant="outlined" sx={{ borderRadius: 0, p: 2, mt: 1 }}>
          <Grid container>
            <Grid
              item
              xs={2}
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                height: "100%",
              }}
            >
              <Avatar alt="nftguy1" src="/avi.png" />
            </Grid>
            <Grid item xs={10}>
              <TextField
                fullWidth
                multiline
                rows={3}
                value={post}
                onChange={(e) => setPost(e.target.value)}
                placeholder="Whats going on?!"
                id="standard-basic"
                label="My tweet"
                variant="standard"
                InputLabelProps={{
                  shrink: true,
                }}
              />
            </Grid>
          </Grid>
          <CardActions
            sx={{
              display: "flex",
              justifyContent: "flex-end",
            }}
          >
            <Button
              disableElevation
              size="small"
              variant="contained"
              disabled={Boolean(post.length <= 0)}
              onClick={createTweet}
              sx={{
                borderRadius: 15,
                p: 0.8,
              }}
            >
              Post
            </Button>
          </CardActions>
        </Card>
        <Stack direction="column">
          {comments.map((comment) => (
            <Card
              variant="outlined"
              key={comment.id}
              sx={{ borderRadius: 0, p: 2 }}
            >
              <Grid container>
                <Grid
                  item
                  xs={2}
                  sx={{
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    height: "100%",
                  }}
                >
                  <Avatar alt="nftguy1" src="/avi2.jpg" />
                </Grid>
                <Grid item xs={10}>
                  <Box p={2}>
                    <Typography variant="body1">{comment.author}</Typography>
                    <Typography color="GrayText" variant="body2">
                      {comment.content}
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      display: "flex",
                      flex: 1,
                    }}
                  >
                    <IconButton
                      onClick={() => likeTweet(address as string, comment.id)}
                    >
                      <FavoriteBorderOutlinedIcon fontSize="small" />
                    </IconButton>

                    <Typography
                      color="GrayText"
                      sx={{
                        alignSelf: "center",
                      }}
                    >
                      {comment.likes.toString()}
                    </Typography>
                  </Box>
                </Grid>
              </Grid>
              <Grid item xs={12}></Grid>
            </Card>
          ))}
        </Stack>
      </Container>
    </Box>
  );
};

export default Home;
